### ISSUE TITLE
Site broke

### ISSUE THREAD

**Issue by blakelapierre** [gulpjs/plugins#168]
http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,author,modified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20

Is returning 404.

Chrome Console:
````
 XHR finished loading: GET "http://gulpjs.com/plugins/blackList.json".
vendor.js:34 GET http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,…odified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20 404 (Not Found)
gulpjs.com/:1 XMLHttpRequest cannot load http://registry.gulpjs.com/_search?fields=name,keywords,rating,description,…odified,homepage,version&from=0&q=keywords:gulpplugin,gulpfriendly&size=20. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gulpjs.com' is therefore not allowed access. The response had HTTP status code 404.
vendor.js:34 TypeError: Cannot read property 'hits' of undefined
    at formatData (http://gulpjs.com/plugins/js/app.js:1:498)
    at http://gulpjs.com/plugins/js/vendor.js:34:875
    at Array.forEach (native)
    at forEach (http://gulpjs.com/plugins/js/vendor.js:32:1396)
    at transformData (http://gulpjs.com/plugins/js/vendor.js:34:893)
    at transformResponse (http://gulpjs.com/plugins/js/vendor.js:34:2052)
    at deferred.promise.then.wrappedErrback (http://gulpjs.com/plugins/js/vendor.js:34:30662)
    at http://gulpjs.com/plugins/js/vendor.js:35:91
    at Scope.$get.Scope.$eval (http://gulpjs.com/plugins/js/vendor.js:35:8463)
    at Scope.$get.Scope.$digest (http://gulpjs.com/plugins/js/vendor.js:35:6316)
````

**Comment by contra** [comment]
I am aware of this, I have received plenty of complaints. The server got destroyed, I am traveling - I will fix it when I have time but I'm busy right now. Use http://npmjs.org it works just fine

**Comment by blakelapierre** [comment]
Cool, didn't see an issue on it, so I thought I should throw one up.

Thanks for managing it!

**Comment by contra** [comment]
fixed
